; ---------------------------------------------------------------------------
; WriteDotEnv.nsh — Write %APPDATA%\openclaw\.env and openclaw.json
; Called after files are installed via the customInstall macro hook.
; ---------------------------------------------------------------------------

Function WriteOpenClawConfig
  ; Ensure config directory exists
  CreateDirectory "$APPDATA\openclaw"

  ; -------------------------------------------------------------------------
  ; Write .env file
  ; -------------------------------------------------------------------------
  FileOpen $0 "$APPDATA\openclaw\.env" w
  FileWrite $0 "# OpenClaw configuration$\r$\n"
  FileWrite $0 "# Generated by installer on $\r$\n"

  ; AI provider API key — only the selected provider's key is non-empty
  ${If} $ApiKeys.AnthropicKey != ""
    FileWrite $0 "ANTHROPIC_API_KEY=$ApiKeys.AnthropicKey$\r$\n"
  ${EndIf}
  ${If} $ApiKeys.OpenAIKey != ""
    FileWrite $0 "OPENAI_API_KEY=$ApiKeys.OpenAIKey$\r$\n"
  ${EndIf}
  ${If} $ApiKeys.GeminiKey != ""
    FileWrite $0 "GEMINI_API_KEY=$ApiKeys.GeminiKey$\r$\n"
  ${EndIf}
  ${If} $ApiKeys.OpenRouterKey != ""
    FileWrite $0 "OPENROUTER_API_KEY=$ApiKeys.OpenRouterKey$\r$\n"
  ${EndIf}

  ; Channel tokens — only write if channel enabled and token provided
  ${If} $Channels.Telegram == "1"
  ${AndIf} $Tokens.TelegramToken != ""
    FileWrite $0 "TELEGRAM_BOT_TOKEN=$Tokens.TelegramToken$\r$\n"
  ${EndIf}
  ${If} $Channels.Discord == "1"
  ${AndIf} $Tokens.DiscordToken != ""
    FileWrite $0 "DISCORD_BOT_TOKEN=$Tokens.DiscordToken$\r$\n"
  ${EndIf}
  ${If} $Channels.Slack == "1"
  ${AndIf} $Tokens.SlackBotToken != ""
    FileWrite $0 "SLACK_BOT_TOKEN=$Tokens.SlackBotToken$\r$\n"
  ${EndIf}
  ${If} $Channels.Slack == "1"
  ${AndIf} $Tokens.SlackAppToken != ""
    FileWrite $0 "SLACK_APP_TOKEN=$Tokens.SlackAppToken$\r$\n"
  ${EndIf}

  FileClose $0

  ; -------------------------------------------------------------------------
  ; Write openclaw.json config file
  ; -------------------------------------------------------------------------
  FileOpen $0 "$APPDATA\openclaw\openclaw.json" w
  FileWrite $0 "{$\r$\n"
  FileWrite $0 '  "gateway": { "mode": "local", "port": 18789, "bind": "loopback", "auth": { "mode": "none" } },$\r$\n'
  FileWrite $0 '  "channels": {$\r$\n'

  ; Build channels JSON — track whether we need a comma separator
  StrCpy $R0 "0"   ; R0 = written count (for comma logic)

  ${If} $Channels.WebChat == "1"
    FileWrite $0 '    "webchat": { "enabled": true }'
    StrCpy $R0 "1"
  ${EndIf}

  ${If} $Channels.Telegram == "1"
    ${If} $R0 == "1"
      FileWrite $0 ",$\r$\n"
    ${EndIf}
    FileWrite $0 '    "telegram": { "enabled": true }'
    StrCpy $R0 "1"
  ${EndIf}

  ${If} $Channels.Discord == "1"
    ${If} $R0 == "1"
      FileWrite $0 ",$\r$\n"
    ${EndIf}
    FileWrite $0 '    "discord": { "enabled": true }'
    StrCpy $R0 "1"
  ${EndIf}

  ${If} $Channels.Slack == "1"
    ${If} $R0 == "1"
      FileWrite $0 ",$\r$\n"
    ${EndIf}
    FileWrite $0 '    "slack": { "enabled": true }'
    StrCpy $R0 "1"
  ${EndIf}

  ${If} $Channels.WhatsApp == "1"
    ${If} $R0 == "1"
      FileWrite $0 ",$\r$\n"
    ${EndIf}
    FileWrite $0 '    "whatsapp": { "enabled": true }'
  ${EndIf}

  FileWrite $0 "$\r$\n  }$\r$\n"
  FileWrite $0 "}$\r$\n"
  FileClose $0

  ; -------------------------------------------------------------------------
  ; Handle startup registry entry
  ; -------------------------------------------------------------------------
  ${If} $InstallOptions.StartAtLogin == "1"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "OpenClaw" "$INSTDIR\OpenClaw.exe"
  ${Else}
    DeleteRegValue HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "OpenClaw"
  ${EndIf}

  ; -------------------------------------------------------------------------
  ; Handle desktop shortcut (electron-builder handles start menu by default)
  ; -------------------------------------------------------------------------
  ${If} $InstallOptions.DesktopShortcut == "1"
    CreateShortcut "$DESKTOP\OpenClaw.lnk" "$INSTDIR\OpenClaw.exe"
  ${Else}
    Delete "$DESKTOP\OpenClaw.lnk"
  ${EndIf}

FunctionEnd
